### PR TITLE
Various fixes for new EKAT

### LINKED ISSUE #411: Using Kokkos to select the device type in build-haero.
(Moved from the mam4xx repo):

Currently in the build-haero script (https://github.com/eagles-project/mam4xx/blob/main/build-haero.sh) we pass an argument with the device type (DEVICE=$2). However, Kokkos has a feature that automatically select this device type. I have used this feature with NVIDIA GPUs, so I do not know if it works in other type of devices.

To do this we must pass a nvcc_wraper to the KOKKOS_CXX_COMPILER flag in the cmake configuration of kokkos and the library that uses kokkos.

One example using this feature is at: https://github.com/sandialabs/TChem/blob/main/scripts/master_bld.sh
In particular, check the following lines:
Line 12
Line 94
Line 147

Lines 246 to 252.

In this script, we select to build the library (tchem) with or without CUDA. Then Kokkos looks for the type of device.

@odiazib

### PR DESCRIPTION
**Pull request by jeff-cohere**
Every time we update EKAT, we inherit whatever changes have been made since the last time. And sometimes there are a lot! This PR addresses the latest batch of issues.

Closes #411

### CODE REVIEW

**Comment by jeff-cohere** [comment]
@odiazib , I eliminated the old code that requires us to specify the specific device for Kokkos. Seems to work! Give it a try in this branch if you're interested.

**Review by pbosler — APPROVED** [review]
Tried with cuda. works.

**Comment by mjs271** [comment]
I still seem to be getting fpe errors 😕
```
/haero/ext/ekat/src/ekat/util/ekat_arch.cpp:8:
/haero/ext/ekat/src/ekat/util/ekat_feutils.hpp:16:40: error: no member named '__control' in 'fenv_t'
  return fegetenv (&fenv) ? -1 : (fenv.__control & FE_ALL_EXCEPT);
                                  ~~~~ ^
/haero/ext/ekat/src/ekat/util/ekat_feutils.hpp:27:22: error: no member named '__control' in 'fenv_t'
  old_excepts = fenv.__control & FE_ALL_EXCEPT;
                ~~~~ ^
/haero/ext/ekat/src/ekat/util/ekat_feutils.hpp:30:8: error: no member named '__control' in 'fenv_t'
  fenv.__control &= ~new_excepts;
  ~~~~ ^
/haero/ext/ekat/src/ekat/util/ekat_feutils.hpp:31:8: error: no member named '__mxcsr' in 'fenv_t'
  fenv.__mxcsr   &= ~(new_excepts << 7);
  ~~~~ ^
/haero/ext/ekat/src/ekat/util/ekat_feutils.hpp:44:22: error: no member named '__control' in 'fenv_t'
  old_excepts = fenv.__control & FE_ALL_EXCEPT;
                ~~~~ ^
/haero/ext/ekat/src/ekat/util/ekat_feutils.hpp:47:8: error: no member named '__control' in 'fenv_t'
  fenv.__control |= new_excepts;
  ~~~~ ^
/haero/ext/ekat/src/ekat/util/ekat_feutils.hpp:48:8: error: no member named '__mxcsr' in 'fenv_t'
  fenv.__mxcsr   |= new_excepts << 7;
  ~~~~ ^
In file included from /haero/ext/ekat/src/ekat/util/ekat_arch.cpp:10:
In file included from /haero/ext/ekat/src/ekat/kokkos/ekat_kokkos_types.hpp:7:
```

**Comment by jeff-cohere** [comment]
Guh. Looks like that will require a fix to EKAT. I don't know why you're the only one who seems to see this, @mjs271 . What kind of Mac is it? Can you copy/paste your cmake configuration command?

If this is a flag in EKAT, this particular bug will have to wait for a later PR.

**Review by overfelt — APPROVED** [review]

**Comment by jeff-cohere** [comment]
@odiazib and @mjs271 , any objection to me merging this PR? Is there anything else either of you would like to test?

**Review by odiazib — APPROVED** [review]

**Review by mjs271 — APPROVED** [review]
I say let's go!

**Pull request merged**
